name: Test Action
on:
  - push

permissions:
  actions: write

concurrency:
  group: test-action
  cancel-in-progress: true

jobs:
  clear-cache:
    name: Clear cache
    runs-on: ubuntu-latest

    steps:
      - name: Clear cache
        run: gh cache delete --repo "${{ github.repository }}" --all || exit 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-check:
    name: Test website
    runs-on: ubuntu-latest
    needs: clear-cache

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Test
        id: test
        uses: ./
        with:
          website-ref: main

      - name: Dump outputs
        run: |
          echo "Cache hit: ${{ steps.test.outputs.cache-hit }}"

  # FIXME: deduplicate
  test-check-cache:
    name: Test website with cache
    runs-on: ubuntu-latest
    needs: test-check

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Test
        id: test
        uses: ./
        with:
          website-ref: main

      - name: Dump outputs
        run: |
          echo "Cache hit: ${{ steps.test.outputs.cache-hit }}"
